version: '3.8'
networks:
  bridge_archee:
    driver: bridge
services:
  java_app:
    build: .
    container_name: java_app
    networks:
      - bridge_archee
  toolbox:
    image : busybox:latest
    container_name : toolbox
    command: sleep 3600
    networks:
      - bridge_archee:
          aliases:
          - helper